# Generated by Django 6.0.2 on 2026-03-25 07:43

import django.core.validators
import django.db.models.deletion
import website.utils.upload_path
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the website. This will be used as the directory name for storing assets.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of the website.",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The URL where the website will be hosted.",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "css",
                    models.FileField(
                        help_text="The CSS file for the website.",
                        upload_to=website.utils.upload_path.upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["css"]
                            )
                        ],
                    ),
                ),
                (
                    "js",
                    models.FileField(
                        help_text="The JavaScript file for the website.",
                        upload_to=website.utils.upload_path.upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["js"]
                            )
                        ],
                    ),
                ),
                (
                    "header",
                    models.FileField(
                        help_text="The header file for the website.",
                        upload_to=website.utils.upload_path.upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["txt"]
                            )
                        ],
                    ),
                ),
                (
                    "footer",
                    models.FileField(
                        help_text="The footer file for the website.",
                        upload_to=website.utils.upload_path.upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["txt"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this website.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="The title of the page.",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The slug for the page.", max_length=255
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of the page.",
                    ),
                ),
                (
                    "meta_og_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The Open Graph type for the page (e.g., 'website', 'article').",
                        max_length=50,
                    ),
                ),
                (
                    "meta_og_image",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="The URL of the Open Graph image for the page.",
                        max_length=500,
                    ),
                ),
                (
                    "content",
                    models.FileField(
                        help_text="The content file for the page.",
                        upload_to=website.utils.upload_path.upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["txt"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "website",
                    models.ForeignKey(
                        help_text="The website to which this page belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="website.website",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded asset file (image or video).",
                        upload_to=website.utils.upload_path.upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                    "svg",
                                    "mp4",
                                    "mov",
                                    "avi",
                                    "mkv",
                                    "webm",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        help_text="Detected asset type.",
                        max_length=10,
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        help_text="Size of the uploaded file in bytes."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "website",
                    models.ForeignKey(
                        help_text="The website to which this asset belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="website.website",
                    ),
                ),
            ],
        ),
    ]
