# Generated by Django 6.0.2 on 2026-03-24 10:44

import django.core.validators
import django.db.models.deletion
import website.utils.asset_upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded asset file (image or video).', upload_to=website.utils.asset_upload_path.asset_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'mp4', 'mov', 'avi', 'mkv', 'webm'])])),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], help_text='Detected asset type.', max_length=10)),
                ('size', models.BigIntegerField(help_text='Size of the uploaded file in bytes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('website', models.ForeignKey(help_text='The website to which this asset belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='website.website')),
            ],
        ),
    ]
