# Generated by Django 6.0.2 on 2026-03-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='Alternative text for the asset.', max_length=255),
        ),
    ]
