# Generated by Django 6.0.2 on 2026-04-10 11:28

import django.core.validators
import website.utils.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_asset_height_asset_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="file",
            field=models.FileField(
                help_text="Uploaded asset file (image or video).",
                upload_to=website.utils.upload_path.upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "webp",
                            "mp4",
                            "mov",
                            "avi",
                            "mkv",
                            "webm",
                        ]
                    )
                ],
            ),
        ),
    ]
