# Generated by Django 6.0.2 on 2026-04-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_alter_asset_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="dynamic_endpoint",
            field=models.URLField(
                blank=True,
                help_text="Optional API endpoint to fetch dynamic data for the page.",
                null=True,
            ),
        ),
    ]
