# Generated by Django 6.0.2 on 2026-04-28 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_page_dynamic_endpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_id",
                    models.IntegerField(
                        help_text="The section ID this property list is associated with."
                    ),
                ),
                (
                    "total_items",
                    models.IntegerField(
                        help_text="The total number of properties in this list."
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[("row", "Row"), ("column", "Column")],
                        help_text="The orientation of the property list.",
                        max_length=10,
                    ),
                ),
                (
                    "items_per_row",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of items per row (applicable if orientation is 'row').",
                        null=True,
                    ),
                ),
                (
                    "item_list",
                    models.JSONField(
                        help_text="A JSON array containing the list of properties. Each property should include details such as title, location, price, etc."
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="The data provider for the property list (e.g., 'booking', 'airbnb').",
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="The type of properties in the list (e.g., 'hotel', 'apartment').",
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="The location associated with the property list (e.g., 'New York City').",
                        max_length=255,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional URL to the source of the property data.",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "website",
                    models.ForeignKey(
                        help_text="The website to which this property list belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_lists",
                        to="website.website",
                    ),
                ),
            ],
        ),
    ]
