# Generated by Django 6.0.2 on 2026-04-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_propertylist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertylist",
            name="section_id",
            field=models.CharField(
                help_text="The section ID this property list is associated with.",
                max_length=100,
            ),
        ),
    ]
