# Generated by Django 6.0.2 on 2026-04-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_alter_propertylist_section_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertylist",
            name="orientation",
            field=models.CharField(
                choices=[("grid", "Grid"), ("list", "List")],
                help_text="The orientation of the property list.",
                max_length=10,
            ),
        ),
    ]
