def demo_listings():
    return [
        {
            "id": 1,
            "title": "Koh Chang Beach House",
            "location": "Ko Chang, Thailand",
            "type": "House",
            "price": 10065,
            "currency": "BDT",
            "rating": 4.5,
            "reviews": 2,
            "is_new": False,
            "features": ["Air Conditioner", "Parking", "Pool"],
            "image": "https://imgservice.smartours.com/600x600/5-star-villa-minutes-from-ai-do-sos%c3%baa-bc-8326287-0.jpg",
            "provider": "booking",
            "provider_label": "Booking.com",
        },
        {
            "id": 2,
            "title": "CHUZ Villas Samui",
            "location": "Koh Samui, Thailand",
            "type": "Villa",
            "price": 15986,
            "currency": "BDT",
            "rating": 4.7,
            "reviews": 61,
            "is_new": False,
            "features": ["Air Conditioner", "Parking", "Pool"],
            "image": "https://imgservice.smartours.com/600x600/addys-villas-us-nokomis-ep-1802506-0.jpg",
            "provider": "expedia",
            "provider_label": "Expedia",
        },
        {
            "id": 3,
            "title": "Pearl of Naithon DF04",
            "location": "Sa Khu, Phuket",
            "type": "Apartment",
            "price": 36608,
            "currency": "BDT",
            "rating": 4.8,
            "reviews": 0,
            "is_new": True,
            "features": ["Air Conditioner", "Parking", "Pool"],
            "image": "https://imgservice.smartours.com/600x600/adriana-luxury-villas-gr-adamantas-bc-11661710-0.jpg",
            "provider": "booking",
            "provider_label": "Booking.com",
        },
        {
            "id": 4,
            "title": "Alanta Villa",
            "location": "Ko Lanta, Thailand",
            "type": "Villa",
            "price": 22791,
            "currency": "BDT",
            "rating": 4.6,
            "reviews": 38,
            "is_new": False,
            "features": ["Air Conditioner", "Parking", "Pet Friendly"],
            "image": "https://imgservice.smartours.com/600x600/aethra-vegan-caves-gr-pyrgos-bc-11698447-0.jpg",
            "provider": "expedia",
            "provider_label": "Expedia",
        },
        {
            "id": 5,
            "title": "Na Tara Resort",
            "location": "Ko Chang, Thailand",
            "type": "Resort",
            "price": 3484,
            "currency": "BDT",
            "rating": 4.3,
            "reviews": 24,
            "is_new": False,
            "features": ["Air Conditioner", "Parking", "Pool"],
            "image": "https://imgservice.smartours.com/600x600/alanta-villa-th-ko-lanta-ep-9098424-0.jpg",
            "provider": "booking",
            "provider_label": "Booking.com",
        },
        {
            "id": 6,
            "title": "Phangan Luggage Storage",
            "location": "Ban Tai, Koh Phangan",
            "type": "Hostel",
            "price": 1538,
            "currency": "BDT",
            "rating": 4.0,
            "reviews": 2,
            "is_new": False,
            "features": ["Air Conditioner", "Parking", "Storage"],
            "image": "https://imgservice.smartours.com/600x600/almost-heaven-mountain-cabi-us-murphy-bc-9179596-0.jpg",
            "provider": "booking",
            "provider_label": "Booking.com",
        },
        {
            "id": 7,
            "title": "TheCharm Resort",
            "location": "Phuket, Thailand",
            "type": "Apartment",
            "price": 11903,
            "currency": "BDT",
            "rating": 4.4,
            "reviews": 8,
            "is_new": False,
            "features": ["Air Conditioner", "Parking", "Pool"],
            "image": "https://imgservice.smartours.com/600x600/antico-borgo-it-san-mauro-castelverde-bc-8514085-0.jpg",
            "provider": "booking",
            "provider_label": "Booking.com",
        },
        {
            "id": 8,
            "title": "Les Tortugas",
            "location": "Hua Hin, Thailand",
            "type": "Apartment",
            "price": 20431,
            "currency": "BDT",
            "rating": 0,
            "reviews": 0,
            "is_new": True,
            "features": ["Air Conditioner", "Parking", "Pool"],
            "image": "https://imgservice.smartours.com/600x600/apartam-do-santiago-de-los-caballeros-bc-6972616-0.jpg",
            "provider": "booking",
            "provider_label": "Booking.com",
        },
    ]
