def demo_listings():
    return [
        {
        "id": 1,
        "title": "Koh Chang Beach House",
        "location": "Ko Chang, Thailand",
        "type": "House",
        "price": 10065,
        "currency": "BDT",
        "rating": 4.5,
        "reviews": 2,
        "is_new": False,
        "features": ["Air Conditioner", "Parking", "Pool"],
        "image": "/media/listings/koh-chang.jpg",
        "provider": "booking",
        "provider_label": "Booking.com",
        "cta": "Check Dates"
        },
        {
        "id": 2,
        "title": "CHUZ Villas Samui",
        "location": "Koh Samui, Thailand",
        "type": "Villa",
        "price": 15986,
        "currency": "BDT",
        "rating": 4.7,
        "reviews": 61,
        "is_new": False,
        "features": ["Air Conditioner", "Parking", "Pool"],
        "image": "/media/listings/chuz-villa.jpg",
        "provider": "expedia",
        "provider_label": "Expedia",
        "cta": "Check Dates"
        },
        {
        "id": 3,
        "title": "Pearl of Naithon DF04",
        "location": "Sa Khu, Phuket",
        "type": "Apartment",
        "price": 36608,
        "currency": "BDT",
        "rating": 4.8,
        "reviews": 0,
        "is_new": True,
        "features": ["Air Conditioner", "Parking", "Pool"],
        "image": "/media/listings/naithon.jpg",
        "provider": "booking",
        "provider_label": "Booking.com",
        "cta": "Check Dates"
        },
        {
        "id": 4,
        "title": "Alanta Villa",
        "location": "Ko Lanta, Thailand",
        "type": "Villa",
        "price": 22791,
        "currency": "BDT",
        "rating": 4.6,
        "reviews": 38,
        "is_new": False,
        "features": ["Air Conditioner", "Parking", "Pet Friendly"],
        "image": "/media/listings/alanta.jpg",
        "provider": "expedia",
        "provider_label": "Expedia",
        "cta": "Check Dates"
        },
        {
        "id": 5,
        "title": "Na Tara Resort",
        "location": "Ko Chang, Thailand",
        "type": "Resort",
        "price": 3484,
        "currency": "BDT",
        "rating": 4.3,
        "reviews": 24,
        "is_new": False,
        "features": ["Air Conditioner", "Parking", "Pool"],
        "image": "/media/listings/natara.jpg",
        "provider": "booking",
        "provider_label": "Booking.com",
        "cta": "Check Dates"
        },
        {
        "id": 6,
        "title": "Phangan Luggage Storage",
        "location": "Ban Tai, Koh Phangan",
        "type": "Hostel",
        "price": 1538,
        "currency": "BDT",
        "rating": 4.0,
        "reviews": 2,
        "is_new": False,
        "features": ["Air Conditioner", "Parking", "Storage"],
        "image": "/media/listings/phangan.jpg",
        "provider": "booking",
        "provider_label": "Booking.com",
        "cta": "Check Dates"
        },
        {
        "id": 7,
        "title": "TheCharm Resort",
        "location": "Phuket, Thailand",
        "type": "Apartment",
        "price": 11903,
        "currency": "BDT",
        "rating": 4.4,
        "reviews": 8,
        "is_new": False,
        "features": ["Air Conditioner", "Parking", "Pool"],
        "image": "/media/listings/charm.jpg",
        "provider": "booking",
        "provider_label": "Booking.com",
        "cta": "Check Dates"
        },
        {
        "id": 8,
        "title": "Les Tortugas",
        "location": "Hua Hin, Thailand",
        "type": "Apartment",
        "price": 20431,
        "currency": "BDT",
        "rating": 0,
        "reviews": 0,
        "is_new": True,
        "features": ["Air Conditioner", "Parking", "Pool"],
        "image": "/media/listings/tortugas.jpg",
        "provider": "booking",
        "provider_label": "Booking.com",
        "cta": "Check Dates"
        }
  ]